export type ErrorType = {
  MAX_PRODUCTS_REACHED: string;
  ORDER_ALREADY_IN_CHECKOUT: string;
  ORDER_IS_EMPTY: string;
  ORDER_IS_NOT_OPEN: string;
};

export const error: ErrorType = {
  MAX_PRODUCTS_REACHED: "MAX_PRODUCTS_REACHED",
  ORDER_ALREADY_IN_CHECKOUT: " ORDER_ALREADY_IN_CHECKOUT",
  ORDER_IS_EMPTY: "ORDER_IS_EMPTY",
  ORDER_IS_NOT_OPEN: "ORDER_IS_NOT_OPEN",
};
